export default [
  { label: 'ANSI', width: 'label', group: true },

  { name: 'Esc', code: 'ESC', keys: 'esc' },
  { width: 1000 },
  { name: 'F1', code: 'F1', keys: 'f1' },
  { name: 'F2', code: 'F2', keys: 'f2' },
  { name: 'F3', code: 'F3', keys: 'f3' },
  { name: 'F4', code: 'F4', keys: 'f4' },
  { width: 500 },
  { name: 'F5', code: 'F5', keys: 'f5' },
  { name: 'F6', code: 'F6', keys: 'f6' },
  { name: 'F7', code: 'F7', keys: 'f7' },
  { name: 'F8', code: 'F8', keys: 'f8' },
  { width: 500 },
  { name: 'F9', code: 'F9', keys: 'f9' },
  { name: 'F10', code: 'F10', keys: 'f10' },
  { name: 'F11', code: 'F11', keys: 'f11' },
  { name: 'F12', code: 'F12', keys: 'f12' },
  { width: 250 },
  { name: 'Print Screen', code: 'PSCRN' },
  { name: 'Scroll Lock', code: 'SLCK' },
  { name: 'Pause', code: 'PAUSE_BREAK' },
  { width: 0 },

  { name: '~\n`', code: 'GRAVE', keys: '`' },
  { name: '!\n1', code: 'NUMBER_1', keys: '1' },
  { name: '@\n2', code: 'NUMBER_2', keys: '2' },
  { name: '#\n3', code: 'NUMBER_3', keys: '3' },
  { name: '$\n4', code: 'NUMBER_4', keys: '4' },
  { name: '%\n5', code: 'NUMBER_5', keys: '5' },
  { name: '^\n6', code: 'NUMBER_6', keys: '6' },
  { name: '&\n7', code: 'NUMBER_7', keys: '7' },
  { name: '*\n8', code: 'NUMBER_8', keys: '8' },
  { name: '(\n9', code: 'NUMBER_9', keys: '9' },
  { name: ')\n0', code: 'NUMBER_0', keys: '0' },
  { name: '_\n-', code: 'MINUS', keys: '-' },
  { name: '+\n=', code: 'EQUAL', keys: '=' },
  { name: 'Back Space', code: 'BACKSPACE', keys: 'backspace', width: 2000 },
  { width: 250 },
  { name: 'Insert', code: 'INSERT', keys: 'insert' },
  { name: 'Home', code: 'HOME', keys: 'home' },
  { name: 'Page Up', code: 'PAGE_UP', keys: 'pageup' },
  { width: 250 },
  { name: 'Num Lock', code: 'LOCKING_NUM', keys: 'num' },
  { name: '/', code: 'KP_DIVIDE', keys: 'num_divide' },
  { name: '*', code: 'KP_MULTIPLY', keys: 'num_multiply' },
  { name: '-', code: 'KP_MINUS', keys: 'num_subtract' },
  { width: 0 },

  { name: 'Tab', code: 'TAB', keys: 'tab', width: 1500 },
  { name: 'q', code: 'Q', keys: 'q' },
  { name: 'w', code: 'W', keys: 'w' },
  { name: 'e', code: 'E', keys: 'e' },
  { name: 'r', code: 'R', keys: 'r' },
  { name: 't', code: 'T', keys: 't' },
  { name: 'y', code: 'Y', keys: 'y' },
  { name: 'u', code: 'U', keys: 'u' },
  { name: 'i', code: 'I', keys: 'i' },
  { name: 'o', code: 'O', keys: 'o' },
  { name: 'p', code: 'P', keys: 'p' },
  { name: '{\n[', code: 'LEFT_BRACKET', keys: '[' },
  { name: '}\n]', code: 'RIGHT_BRACKET', keys: ']' },
  { name: '|\n\\', code: 'BACKSLASH', keys: '\\', width: 1500 },
  { width: 250 },
  { name: 'Del', code: 'DEL', keys: 'delete' },
  { name: 'End', code: 'END', keys: 'end' },
  { name: 'Page Down', code: 'PAGE_DOWN', keys: 'pagedown' },
  { width: 250 },
  { name: '7', code: 'KP_NUMBER_7', keys: 'num_7' },
  { name: '8', code: 'KP_NUMBER_8', keys: 'num_8' },
  { name: '9', code: 'KP_NUMBER_9', keys: 'num_9' },
  { name: '+', code: 'KP_PLUS', keys: 'num_add' },
  { width: 0 },

  { name: 'Caps Lock', code: 'CAPSLOCK', keys: 'caps_lock', width: 1750 },
  { name: 'a', code: 'A', keys: 'a' },
  { name: 's', code: 'S', keys: 's' },
  { name: 'd', code: 'D', keys: 'd' },
  { name: 'f', code: 'F', keys: 'f' },
  { name: 'g', code: 'G', keys: 'g' },
  { name: 'h', code: 'H', keys: 'h' },
  { name: 'j', code: 'J', keys: 'j' },
  { name: 'k', code: 'K', keys: 'k' },
  { name: 'l', code: 'L', keys: 'l' },
  { name: ':\n;', code: 'SEMICOLON', keys: ';' },
  { name: '"\n\'', code: 'SQT', keys: "'" },
  { name: 'Enter', code: 'ENTER', keys: 'enter', width: 2250 },
  { width: 3500 },
  { name: '4', code: 'KP_NUMBER_4', keys: 'num_4' },
  { name: '5', code: 'KP_NUMBER_5', keys: 'num_5' },
  { name: '6', code: 'KP_NUMBER_6', keys: 'num_6' },
  { name: ',', code: 'KP_COMMA' },
  { width: 0 },

  { name: 'Left Shift', code: 'LSHIFT', keys: 'shift', width: 2250 },
  { name: 'z', code: 'Z', keys: 'z' },
  { name: 'x', code: 'X', keys: 'x' },
  { name: 'c', code: 'C', keys: 'c' },
  { name: 'v', code: 'V', keys: 'v' },
  { name: 'b', code: 'B', keys: 'b' },
  { name: 'n', code: 'N', keys: 'n' },
  { name: 'm', code: 'M', keys: 'm' },
  { name: '<\n,', code: 'COMMA', keys: ',' },
  { name: '>\n.', code: 'DOT', keys: '.' },
  { name: '?\n/', code: 'SLASH', keys: '/' },
  { name: 'Right Shift', code: 'RIGHT_SHIFT', width: 2750 },
  { width: 1250 },
  { name: 'Up', code: 'UP', keys: 'up' },
  { width: 1250 },
  { name: '1', code: 'KP_NUMBER_1', keys: 'num_1' },
  { name: '2', code: 'KP_NUMBER_2', keys: 'num_2' },
  { name: '3', code: 'KP_NUMBER_3', keys: 'num_3' },
  { name: '=', code: 'KP_EQUAL' },
  { width: 0 },

  { name: 'Left Ctrl', code: 'LCTL', keys: 'ctrl', width: 1250 },
  { name: 'Left OS', code: 'LGUI', keys: 'cmd', width: 1250 },
  { name: 'Left Alt', code: 'LALT', keys: 'alt', width: 1250 },
  { name: 'Space', code: 'SPACE', keys: 'space', width: 6250 },
  { name: 'Right Alt', code: 'RALT', width: 1250 },
  { name: 'Right OS', code: 'RGUI', width: 1250 },
  { name: 'Menu', code: 'K_MENU', width: 1250 },
  { name: 'Right Ctrl', code: 'RCTL', width: 1250 },
  { width: 250 },
  { name: 'Left', code: 'LEFT', keys: 'left' },
  { name: 'Down', code: 'DOWN', keys: 'down' },
  { name: 'Right', code: 'RIGHT', keys: 'right' },
  { width: 250 },
  { name: '0', code: 'KP_NUMBER_0', keys: 'num_0', width: 2000 },
  { name: '.', code: 'KP_DOT', keys: 'num_decimal' },
  { name: 'Enter', code: 'KP_ENTER', keys: 'num_enter' },

  { label: 'Shifted symbols', width: 'label' },

  { name: '~', code: 'TILDE', keys: '~' },
  { name: '!', code: 'EXCLAMATION', keys: '!' },
  { name: '@', code: 'AT', keys: '@' },
  { name: '#', code: 'HASH', keys: '#' },
  { name: '$', code: 'DOLLAR', keys: '$' },
  { name: '%', code: 'PERCENT', keys: '%' },
  { name: '^', code: 'CARET', keys: '^' },
  { name: '&', code: 'AMPERSAND', keys: '&' },
  { name: '*', code: 'ASTERISK', keys: '*' },
  { name: '(', code: 'LPAR', keys: '(' },
  { name: ')', code: 'RPAR', keys: ')' },
  { name: '_', code: 'UNDERSCORE', keys: '_' },
  { name: '+', code: 'PLUS', keys: '+' },
  { name: '{', code: 'LEFT_BRACE', keys: '{' },
  { name: '}', code: 'RIGHT_BRACE', keys: '}' },
  { name: '<', code: 'LESS_THAN', keys: '<' },
  { name: '>', code: 'GREATER_THAN', keys: '>' },
  { name: ':', code: 'COLON', keys: ':' },
  { name: '|', code: 'PIPE', keys: '|' },
  { name: '?', code: 'QUESTION', keys: '?' },
  { name: '"', code: 'DOUBLE_QUOTES', keys: '"' }
];
